### ISSUE TITLE
Failing WRITE/READ directed test

### ISSUE THREAD

**Issue by ghost** [Furqan-Lamp/AHB-Lite-Slave-Design-Verification-Environment#1]
I am doing a simple directed test by writing to first 100 locations and than reading from there. Most of the read transaction fail in comparison except for a few. I am using the following piece of code in the main() task.

- I have also set the transaction type to a fixed (NONSEQ) one type to keep it simple.

```
    for (int i=0 ;i<100; i++) begin
      pre_routine();
      rPack.HWDATA = i;
      rPack.HADDR = i;
      rPack.HWRITE = 1;
      rPack.HTRANS = 2;
      rPack.HSIZE = 0;
      post_routine();
      rPack.printR("GEN-WRITE");
    end
    for (int i=0 ;i<100; i++) begin
      pre_routine();
      rPack.HWDATA = i;
      rPack.HADDR = i;
      rPack.HWRITE = 0;
      rPack.HTRANS = 2;
      rPack.HSIZE = 0;
      post_routine();
      rPack.printR("GEN-READ");
    end
```

The failures are at 32 bit boundaries. For example, at location 31 and 32, than at 63 and 64, and so on. Apart from that, for a bytes sized read/write, first 16 or so transaction also fail which refer to first four words.

**Comment by Furqan-Lamp** [comment]
Thank you for your email. Theek kr dy issu

**Comment by ghost** [comment]
The failures are at 32 bit boundaries. For example, at location 31 and 32, than at 63 and 64, and so on. Apart from that, for a bytes sized read/write, first 16 or so transaction also fail which refer to first four words.

**Comment by ghost** [comment]
I modified my directed test. Did it for `BYTE`, and the tests do pass. But the interface (sort of) shows garbage data instead of my `'b0 `initiated `HWDATA` overwritten by `mem[i]=i` at proper offset for each address. The modified tests also required me to check if rand logic in transaction for `HWDATA` needs to be non-random. So, I removed the rand in that as well. EDA playground for this issue is at: [https://www.edaplayground.com/x/rjz9](https://www.edaplayground.com/x/rjz9)

```
    for (int i=0 ;i<100; i++) begin
      pre_routine();
      rPack.HADDR = i;//4*i;
      rPack.HWDATA = i;
//       rPack.HWDATA = 128'b0;
      rPack.HWDATA[(rPack.HADDR%16)*8 +:8] = i;
      rPack.HWRITE = 1;
      rPack.HTRANS = 2;
      rPack.HSIZE = 0;
      post_routine();
//       rPack.printR("GEN-WRITE");
    end
    for (int i=0 ;i<100; i++) begin
      pre_routine();
      rPack.HADDR = i;//4*i;
      rPack.HWDATA = 0;
      rPack.HWRITE = 0;
      rPack.HTRANS = 2;
      rPack.HSIZE = 0;
      post_routine();
//       rPack.printR("GEN-READ");
    end
```

Closing this issue, since `write/read` test is passing for bytes. I'll create a separate issue if the error happens for other data types.

**Comment by ghost** [comment]
The correct code is as following:
```

    for (int i=0 ;i<100; i++) begin
      pre_routine();
      rPack.HADDR = i;//4*i;
//       rPack.HWDATA = 128'b0;
//       rPack.HWDATA[(rPack.HADDR%16)*8 +:8] = i;
      rPack.HWDATA[(rPack.HADDR%16)*8 +:8] = i;
      rPack.HWRITE = 1;
      rPack.HTRANS = 3;
      rPack.HSIZE = 0;
      post_routine();
//       rPack.printR("GEN-WRITE");
    end
    for (int i=0 ;i<100; i++) begin
      pre_routine();
      rPack.HADDR = i;//4*i;
      rPack.HWDATA = 0;
      rPack.HWRITE = 0;
      rPack.HTRANS = 3;
      rPack.HSIZE = 0;
      post_routine();
//       rPack.printR("GEN-READ");
    end
```
